shinyUI(navbarPage(title = "Améginat-IF", 
                   id = "nav",
                   theme = shinytheme("sandstone"),
                   tabPanel("Scénario",
                            div(class="outer",
                                tags$head(
                                  # Include our custom CSS
                                  includeCSS("styles.css")
                                ),
                                leafletOutput("mapindic", width = "100%", height = "100%"),
                                absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                                              draggable = TRUE, top = 80, left = 20, right = "auto", bottom = "auto",
                                              width = 300, height = "auto",
                                              radioButtons("selindex", 
                                                           label = "INDICATEURS",
                                                           choices = list("Population active" = "TOTORI",
                                                                          "Emploi" = "TOTDES",
                                                                          "Solde absolu" = "ABSBAL",
                                                                          "Solde relatif" = "RELBAL",
                                                                          "Autocontention" = "AUTOCONT",
                                                                          "Autosuffisance" = "AUTOSUFF",
                                                                          "Distance moyenne à l'origine" = "AVGDISTORI",
                                                                          "Distance moyenne à destination" = "AVGDISTDES",
                                                                          "Distance totale à l'origine" = "SUMDISTORI",
                                                                          "Distance totale à destination" = "SUMDISTDES"),
                                                           selected = "TOTORI"),
                                              actionButton("index_descr", "Description")
                                ),
                                
                                absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                                              draggable = TRUE, top = 80, left = "auto", right = 20, bottom = "auto",
                                              width = 200, height = "auto",
                                              radioButtons(inputId = "filterpop1",
                                                           label = "FILTRE",
                                                           choices = list("Tout" = "TOU",
                                                                          "Agriculteur" = "AGR",
                                                                          "Artisan-commerçant" = "ART",
                                                                          "Prof. supérieure" = "CAD",
                                                                          "Prof. intermédiaire" = "INT",
                                                                          "Employé" = "EMP",
                                                                          "Ouvrier" = "OUV",
                                                                          "Véhicule particulier" = "VP",
                                                                          "Transport collectif" = "TC",
                                                                          "Non motorisé" = "NM",
                                                                          "Immobile" = "IM"),
                                                           selected = "TOU",
                                                           inline = FALSE)
                                ),
                                
                                absolutePanel(id ="controls",
                                              top = "3%", 
                                              bottom = "auto",
                                              right = "35%",
                                              left = "35%",
                                              class = "panel panel-default",
                                              style = "padding : 0px",
                                              bsCollapse(id = "colbox",
                                                         bsCollapsePanel("CHOISIR UN SCENARIO",
                                                                         radioButtons(inputId = "reloc",
                                                                                      label = "Relocaliser les populations et les activités",
                                                                                      choices = c("Configuration actuelle" = "ACT",
                                                                                                  "Finger plan" = "FIN",
                                                                                                  "Transport-oriented development" = "TOD",
                                                                                                  "Polycentrisation" = "POL",
                                                                                                  "CBDsation" = "CBD"),
                                                                                      selected = "ACT",
                                                                                      inline = FALSE, 
                                                                                      width = "100%"),
                                                                         radioButtons(inputId = "excess",
                                                                                      label = "Agir sur les mobilités résidentielle et professionnelle",
                                                                                      choices = c("Configuration actuelle" = "ACT",
                                                                                                  "Échange d'emploi" = "EMP",
                                                                                                  "Échange de logement" = "RES"),
                                                                                      selected = "ACT",
                                                                                      inline = FALSE, 
                                                                                      width = "100%"),
                                                                         radioButtons(inputId = "modetrans",
                                                                                      label = "Agir sur le mode de transport",
                                                                                      choices = c("Configuration actuelle" = "ACT",
                                                                                                  "Zéro voiture" = "ZVP",
                                                                                                  "Tout voiture" = "TVP",
                                                                                                  "Zéro transport collectf" = "ZTC",
                                                                                                  "Tout transport collectf" = "TTC",
                                                                                                  "Zéro modes doux" = "ZNM",
                                                                                                  "Tout modes doux" = "TNM"),
                                                                                      selected = "ACT", 
                                                                                      width = "100%"),
                                                                         actionButton("config_descr", "Description")
                                                                         
                                                         )
                                              )
                                )
                            )
                   ),
                   tabPanel("Oursins",
                            div(class="outer",
                                tags$head(
                                  # Include our custom CSS
                                  includeCSS("styles.css")
                                ),
                                leafletOutput("mapflow", width = "100%", height = "100%"),
                                absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                                              draggable = FALSE, top = 80, left = 20, right = "auto", bottom = "auto",
                                              width = 300, height = "auto",
                                              selectInput("flucom", 
                                                          label = "CHOISIR UNE COMMUNE",
                                                          choices = sort(muniBound$LIBGEO),
                                                          selected = ""),
                                              radioButtons("fluref", label = "Origine ou destination", choices = c("Origine" = "ORI", "Destination" = "DES"), selected = "ORI"),
                                              radioButtons("fluvar", label = "Quantité", choices = c("Nombre d'individus" = "FLOW", "Cumul de distance" = "SUMDIST"), selected = "FLOW"),
                                              sliderInput("fluthr", label = "Top", min = 2, max = 100, step = 1, value = 3),
                                              actionButton("flux_descr", "Description")
                                ),
                                absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                                              draggable = TRUE, top = 80, left = "auto", right = 20, bottom = "auto",
                                              width = 200, height = "auto",
                                              radioButtons(inputId = "filterpop2",
                                                           label = "FILTRE",
                                                           choices = list("Tout" = "TOU",
                                                                          "Agriculteur" = "AGR",
                                                                          "Artisan-commerçant" = "ART",
                                                                          "Prof. supérieure" = "CAD",
                                                                          "Prof. intermédiaire" = "INT",
                                                                          "Employé" = "EMP",
                                                                          "Ouvrier" = "OUV",
                                                                          "Véhicule particulier" = "VP",
                                                                          "Transport collectif" = "TC",
                                                                          "Non motorisé" = "NM",
                                                                          "Immobile" = "IM"),
                                                           selected = "TOU",
                                                           inline = FALSE)
                                )
                            )
                   ),
                   tabPanel("Structure",
                            div(class="outer",
                                tags$head(
                                  # Include our custom CSS
                                  includeCSS("styles.css")
                                ),
                                leafletOutput("mapstruc", width = "100%", height = "100%"),
                                absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                                              draggable = FALSE, top = 80, left = 20, right = "auto", bottom = "auto",
                                              width = 200, height = "auto",
                                              radioButtons("strucalgo", 
                                                           label = "CHOISIR LA MÉTHODE",
                                                           choices = list("Flux dominants" = "domflo",
                                                                          "Modularité" = "modularity")),
                                              actionButton("fludom_descr", "Description")
                                ),
                                absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                                              draggable = TRUE, top = 80, left = "auto", right = 20, bottom = "auto",
                                              width = 200, height = "auto",
                                              radioButtons(inputId = "filterpop3",
                                                           label = "FILTRE",
                                                           choices = list("Tout" = "TOU",
                                                                          "Agriculteur" = "AGR",
                                                                          "Artisan-commerçant" = "ART",
                                                                          "Prof. supérieure" = "CAD",
                                                                          "Prof. intermédiaire" = "INT",
                                                                          "Employé" = "EMP",
                                                                          "Ouvrier" = "OUV",
                                                                          "Véhicule particulier" = "VP",
                                                                          "Transport collectif" = "TC",
                                                                          "Non motorisé" = "NM",
                                                                          "Immobile" = "IM"),
                                                           selected = "TOU",
                                                           inline = FALSE)
                                )
                            )
                   ),
                   tabPanel("Synthèse",
                            div(class="outer",
                                tags$head(
                                  # Include our custom CSS
                                  includeCSS("styles.css")
                                ),
                                fluidRow(
                                  column(12, verbatimTextOutput("mytext")),
                                  column(3,
                                         absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                                                       draggable = FALSE, top = 120, left = 20, right = "auto", bottom = "auto",
                                                       width = 300, height = "auto",
                                                       radioButtons("varsplit", 
                                                                    label = "CHOISIR LA VARIABLE",
                                                                    choices = list("Mode de transport" = "MODE",
                                                                                   "Catégorie socio-professionnelle" = "CSP",
                                                                                   "Zone géographique" = "GEOCLASS"),
                                                                    selected = "MODE"),
                                                       radioButtons("varindic", 
                                                                    label = "CHOISIR L'INDICATEUR",
                                                                    choices = list("Flux" = "FLOW",
                                                                                   "Distance totale" = "SUMDIST",
                                                                                   "Distance moyenne" = "AVGDIST"),
                                                                    selected = "FLOW"),
                                                       actionButton("synth_descr", "Description")
                                         )),
                                  column(9,
                                plotlyOutput("numsum", height = "70%"))
                            )
                   )
                   )
))